{
 "title": "Flussonic Sessions",
 "time": { "from": "now-6h", "to": "now-1m" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Host:",
    "query": "label_values(flussonic_stream_sessions{job=~\"flussonic\"}, hostname)"
   },
   {
    "name": "stream",
    "label": "Stream",
    "query": "label_values(flussonic_stream_sessions{job=~\"flussonic\"}, stream_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Flussonic Sessions HLS",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(stream_name)(flussonic_stream_sessions{hostname=~\"$node\", stream_type=\"hls\", stream_name=~\"$stream\"})\n",
     "legendFormat": "{{stream_name}}"
    }
   ]
  },
  {
   "title": "Flussonic Sessions DVR",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(stream_name)(flussonic_stream_sessions{hostname=~\"$node\", stream_type=\"hls_dvr\", stream_name=~\"$stream\"})\n",
     "legendFormat": "{{stream_name}}"
    }
   ]
  },
  {
   "title": "Flussonic Sessions HLS summary",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(flussonic_stream_sessions{hostname=~\"$node\", stream_type=\"hls\", stream_name=~\"$stream\"})\n",
     "legendFormat": "summary hls"
    }
   ]
  },
  {
   "title": "Flussonic Sessions DVR summary",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(flussonic_stream_sessions{hostname=~\"$node\", stream_type=\"hls_dvr\", stream_name=~\"$stream\"})\n",
     "legendFormat": "summary dvr"
    }
   ]
  }
 ]
}